backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://cliffs-custom-creations.netlify.app
display_url: https://cliffs-custom-creations.netlify.app

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options:
          ["Coasters", "Tumblers", "Leather Keychains", "Wallets", "Wood Works"] }
      - { label: "Image", name: "image", widget: "image" }
